app:
  asset_domain: static.mydomain.com
  domain: mydomain.com
  name: Prey Fetcher
  prowl_provider_key: PROWL_PROVIDER_KEY_HERE
  version: "3.x"
database:
  development:
    adapter: sqlite3
    database: development.sqlite3
  test:
    adapter: sqlite3
    database: test.sqlite3
  production:
    adapter: mysql
    database: prey_fetcher
    username: prey_fetcher
    password: PASS
    host: localhost
twitter:
  oauth:
    consumer_key: OAuth Key
    consumer_secret: OAuth Secret
    access_key: Registered Site Stream User Key
    access_secret: Registered Site Stream User Secret
