# Replace settings here with settings you don't want to
# commit but want to override settings in config.yaml

# Regular app config
app_asset_domain: static.preyfetcher.com
app_domain: preyfetcher.com
# app_name: Prey Fetcher
# app_prowl_appname: Prey Fetcher
app_prowl_provider_key: 

# Assume development; use SQLite3
db_adapter: mysql
db_host: ifrit.internal.hosts.kicksass.ca
db_database: preyfetcher
db_username: preyfetcher
db_password: 

# Spam filtering settings
# spam_days_ago_for_spam_accounts: 4
# spam_filters_enabled: true
# spam_max_offenses: 3
# spam_low_followers_count: 10

# Twitter configs
twitter_consumer_key: 
twitter_consumer_secret: 
twitter_access_key: 
twitter_access_secret: 
# twitter_site_stream_size: 100
