# Regular app config
app_asset_domain: 0.0.0.0:4567
app_domain: 0.0.0.0:4567
app_name: Prey Fetcher
app_prowl_appname: Prey Fetcher
app_prowl_provider_key: 

# Assume development; use SQLite3
db_adapter: sqlite3
db_host: 
db_database: development.sqlite3
db_username: 
db_password: 

# Spam filtering settings
spam_days_ago_for_spam_accounts: 4
spam_filters_enabled: true
spam_max_offenses: 3
spam_low_followers_count: 10

# Twitter configs
twitter_consumer_key: 
twitter_consumer_secret: 
twitter_access_key: 
twitter_access_secret: 
twitter_site_stream_size: 100
