--- 
pid: tmp/pids/thin.pid
servers: 3
address: 127.0.0.1
port: 17000
timeout: 30
log: log/thin.log
max_conns: 1024
chdir: /home/matt/sites/preyfetcher.com
max_persistent_conns: 512
environment: production
daemonize: true
require: []
